version: 2.1


jobs:
  test:
    working_directory: /go/src/github.com/nht1206/pricetracker
    docker:
      - image: circleci/golang:1.16.3
      - image: circleci/mysql:latest
        environment:
          MYSQL_DATABASE: test_db
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: Do vendoring
          command: go get -d -v ./...
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run unit test
          command: |
            go test -v ./...

  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install curl
          command: |
            apk update
            apk add curl
      - run:
          environment:
            DOCKER_VERSION: 20.10.7
          name: Install docker
          command: |
            curl -so docker-${DOCKER_VERSION}.tgz "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz"
            tar -xvzf docker-${DOCKER_VERSION}.tgz
            chmod +x docker/*
            ln docker/* /usr/local/bin/
      - run:
          name: Setup auth config for docker
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: 
          name: Build and push image to docker hub
          command: |
            docker build -t nht1206/pricetracker:${CIRCLE_SHA1} .
            docker push nht1206/pricetracker:${CIRCLE_SHA1}

workflows:
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - /release-.*/
      - build:
          requires:
            - test
          context: pricetracker
          filters:
            branches:
              ignore:
                - /feature\/.*/      
