apiVersion: v1
kind: PersistentVolume
metadata:
  name: datalog-pv
  labels:
    type: local
spec:
  storageClassName: datalog
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/logs"