apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle:
      postStart:
        httpGet:
          path: /postStart
          port: probe
          httpHeaders:
            - name: Accept
              value: application/json
            - name: User-Agent
              value: MyUserAgent
            - name: Accept
              value: ""
      preStop:
        httpGet:
          path: /preStop
          port: probe