apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica_set_name
  labels:
    # custom label
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  # specify what will be control by this replica set
  selector:
    matchLabels:
      tier: frontend
  # template for the pod may be control by this replica set
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3